### ISSUE TITLE
change uTransport APIs to be async

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-java#124]
On the request of a few developers, we would like to change the UTransport APIs to be async as some transport implementations can benefit from this design. Developers that use the transport can then choose to either block for the API to return or wait for the future to complete.

**Comment by jjj-vtm** [comment]
Hi, I would still prefer to have an explicit result type instead of Void. So instead of:
CompletionStage<Void> send(UMessage message);

the signature
CompletionStage<UResult> send(UMessage message);

is IMHO a little bit cleaner because it avoids exceptions to communicate errors and has an explicit type. Exception creation is horribly slow compared to simple object creation because it by default captures a stack trace. I doubt that this will create any problems but it is another reason to avoid exceptions whenever possilbe.
